version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-jdbc-curse
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mysql-jdbc-curse
      MYSQL_USER: juan
      MYSQL_PASSWORD: juan
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
